server:
  port: 8084

spring:
  application:
    name: eureka-client
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  instance:
    instance-id: eureka-client-two
    appname: ${spring.application.name}}
  client:
    service-url:
      defaultZone:
        http://localhost:8762/eureka